#! /bin/bash

# sysinfo — console util to show concise system info for Linux arch/distro
#
# Author:  Micah Elliott http://MicahElliott.com
# License: WTFPL http://sam.zoy.org/wtfpl/

trim() { local trimres=$(echo $1 |sed "s/^ \+//") }

name=$(hostname)
#glibc=$(rpm -q glibc|uniq)
glibc=$(ls /lib/libc-*.so |head -1 |sed -e 's/.*-//' -e 's/\.so$//')
gcc=$(gcc --version |head -1)
kernel=$(uname -r)
arch=$(uname -m)
#distro=$(for f in /etc/{redhat,SuSE}-release; do test -f $f && head -1 $f; done)
distro=$(lsb_release -i |awk '{print $3}')
release=$(lsb_release -r |awk '{print $2}')
codename=$(lsb_release -c |awk '{print $2}')
freemem=$(free -m |grep Mem |tr -s ' ' |cut -d' ' -f2)
freeswap=$(free -m |grep Swap |tr -s ' ' |cut -d' ' -f2)
trim $(cat /etc/motd |grep "^$(hostname)" |cut -d'-' -f3)
msg=$trimres

test $arch = "ia64" && {
   vendor=$(grep '^vendor' /proc/cpuinfo |uniq |cut -d: -f2)
   fam=$(grep '^family' /proc/cpuinfo |uniq |cut -d: -f2)
   mhz=$(grep '^cpu MHz' /proc/cpuinfo |uniq |cut -d: -f2)
   proc="$vendor$fam$mhz"
   nprocs=$(grep '^processor' /proc/cpuinfo |wc -l |tr -s ' ')
   cache=$(grep 'Size' /proc/pal/cpu0/cache_info |tail -1 |cut -d: -f2)
} || {
   proc=$(grep "model name" /proc/cpuinfo |uniq |cut -d: -f2 |tr -s ' ')
   nprocs=$(grep processor /proc/cpuinfo |wc -l |tr -d ' ' |tr -s ' ')
   cache=$(awk '/^cache/ {print $4}' /proc/cpuinfo |head -1)
}

echo "hostname: $name"
echo "distro:   $distro"
echo "release:  $release"
echo "codename: $codename"
echo "glibc:    $glibc"
echo "gcc:      $gcc"
echo "kernel:   $kernel"
echo "arch:     $arch"
echo "procs:   $proc (x$nprocs)"
echo "cache:    $cache KB"
echo "ram:      $freemem MB"
echo "swap:     $freeswap MB"
#test -n "$msg" && echo "Message:       $msg"
